spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petClinic
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Optional: Additional Hibernate or datasource settings
logging:
  level:
    org:
      hibernate:
        SQL: debug
